function f = calc_f(in1,in2,in3)
%CALC_F
%    F = CALC_F(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    14-Dec-2023 14:37:35

theta = in1(3,:);
theta_dot = in2(1,:);
v = in1(4,:);
v_dot = in2(2,:);
f = [v.*cos(theta);v.*sin(theta);theta_dot;v_dot];
end
