function f_disc = calc_f_disc(in1,in2,dt,in4)
%CALC_F_DISC
%    F_DISC = CALC_F_DISC(IN1,IN2,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    14-Dec-2023 14:37:35

theta = in1(3,:);
theta_dot = in2(1,:);
v = in1(4,:);
v_dot = in2(2,:);
x = in1(1,:);
y = in1(2,:);
f_disc = [x+dt.*v.*cos(theta);y+dt.*v.*sin(theta);theta+dt.*theta_dot;v+dt.*v_dot];
end
