function A_disc = calc_A_disc(in1,in2,dt,in4)
%calc_A_disc
%    A_disc = calc_A_disc(IN1,IN2,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    14-Dec-2023 14:37:35

theta = in1(3,:);
v = in1(4,:);
t2 = cos(theta);
t3 = sin(theta);
A_disc = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-dt.*t3.*v,dt.*t2.*v,1.0,0.0,dt.*t2,dt.*t3,0.0,1.0],[4,4]);
end
