function A_disc = bike_A_disc(in1,in2,dt,in4)
%bike_A_disc
%    A_disc = bike_A_disc(IN1,IN2,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    14-Jan-2024 22:39:12

V = in1(4,:);
delta = in2(2,:);
yaw = in1(3,:);
t2 = cos(yaw);
t3 = sin(yaw);
A_disc = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-V.*dt.*t3,V.*dt.*t2,1.0,0.0,dt.*t2,dt.*t3,dt.*tan(delta).*(5.0./1.2e+1),1.0],[4,4]);
end
