function B_disc = bike_B_disc(in1,in2,dt,in4)
%bike_B_disc
%    B_disc = bike_B_disc(IN1,IN2,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    14-Jan-2024 22:39:12

V = in1(4,:);
delta = in2(2,:);
B_disc = reshape([0.0,0.0,0.0,dt,0.0,0.0,V.*dt.*(tan(delta).^2+1.0).*(5.0./1.2e+1),0.0],[4,2]);
end
