function f_disc = bike_f_disc(in1,in2,dt,in4)
%BIKE_F_DISC
%    F_DISC = BIKE_F_DISC(IN1,IN2,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    14-Jan-2024 22:39:12

V = in1(4,:);
V_dot = in2(1,:);
delta = in2(2,:);
x = in1(1,:);
y = in1(2,:);
yaw = in1(3,:);
f_disc = [x+V.*dt.*cos(yaw);y+V.*dt.*sin(yaw);yaw+V.*dt.*tan(delta).*(5.0./1.2e+1);V+V_dot.*dt];
end
