function f = bike_f(in1,in2,in3)
%BIKE_F
%    F = BIKE_F(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    14-Jan-2024 22:39:12

V = in1(4,:);
V_dot = in2(1,:);
delta = in2(2,:);
yaw = in1(3,:);
f = [V.*cos(yaw);V.*sin(yaw);V.*tan(delta).*(5.0./1.2e+1);V_dot];
end
