function A_disc = quad2d_A_disc(in1,in2,dt,in4)
%quad2d_A_disc
%    A_disc = quad2d_A_disc(IN1,IN2,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    26-Jan-2024 18:08:52

F1 = in2(1,:);
F2 = in2(2,:);
theta = in1(3,:);
t2 = F1+F2;
A_disc = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,dt.*t2.*cos(theta),-dt.*t2.*sin(theta),0.0,dt,0.0,0.0,1.0,0.0,0.0,0.0,dt,0.0,0.0,1.0,0.0,0.0,0.0,dt,0.0,0.0,1.0],[6,6]);
end
