function f_disc = quad2d_f_disc(in1,in2,dt,in4)
%QUAD2D_F_DISC
%    F_DISC = QUAD2D_F_DISC(IN1,IN2,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    26-Jan-2024 18:08:52

F1 = in2(1,:);
F2 = in2(2,:);
theta = in1(3,:);
theta_dot = in1(6,:);
vx = in1(4,:);
vz = in1(5,:);
x = in1(1,:);
z = in1(2,:);
t2 = F1+F2;
f_disc = [x+dt.*vx;z+dt.*vz;theta+dt.*theta_dot;vx+dt.*t2.*sin(theta);vz+dt.*(t2.*cos(theta)-9.81e+2./1.0e+2);theta_dot+dt.*(F1.*2.5e+1-F2.*2.5e+1)];
end
