function B_disc = quad2d_B_disc(in1,in2,dt,in4)
%quad2d_B_disc
%    B_disc = quad2d_B_disc(IN1,IN2,DT,IN4)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    26-Jan-2024 18:08:52

theta = in1(3,:);
t2 = cos(theta);
t3 = sin(theta);
t6 = dt.*2.5e+1;
t4 = dt.*t2;
t5 = dt.*t3;
B_disc = reshape([0.0,0.0,0.0,t5,t4,t6,0.0,0.0,0.0,t5,t4,-t6],[6,2]);
end
