function f = quad2d_f(in1,in2,in3)
%QUAD2D_F
%    F = QUAD2D_F(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    26-Jan-2024 18:08:52

F1 = in2(1,:);
F2 = in2(2,:);
theta = in1(3,:);
theta_dot = in1(6,:);
vx = in1(4,:);
vz = in1(5,:);
t2 = F1+F2;
f = [vx;vz;theta_dot;t2.*sin(theta);t2.*cos(theta)-9.81e+2./1.0e+2;F1.*2.5e+1-F2.*2.5e+1];
end
